import {
  Accessibility,
  Baby,
  Banknote,
  Bath,
  Bed,
  Beef,
  Beer,
  Bike,
  Binoculars,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  CakeSlice,
  Camera,
  Car,
  Castle,
  ChefHat,
  CircleParking,
  Coffee,
  Compass,
  Dog,
  Drama,
  FerrisWheel,
  Fish,
  Flower2,
  Footprints,
  Gift,
  GlassWater,
  HeartHandshake,
  Home,
  Hospital,
  IceCream,
  Image,
  Info,
  Landmark,
  Languages,
  Leaf,
  MapPin,
  Mountain,
  Music,
  Navigation,
  Palette,
  Plane,
  QrCode,
  Sailboat,
  Search,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  Soup,
  Sprout,
  Star,
  Store,
  Sun,
  Moon,
  Tent,
  Ticket,
  Train,
  TreePine,
  Trees,
  Utensils,
  Wallet,
  Warehouse,
  Waves,
  Wifi,
  Wine,
  Apple,
} from "lucide-react";

export const DEFAULT_CATEGORY_ICON = "map-marker-outline";

export const CATEGORY_ICON_GROUPS = [
  {
    label: "Travel essentials",
    icons: [
      "map-marker-outline",
      "map-search-outline",
      "compass-outline",
      "sign-direction",
      "ticket-confirmation-outline",
      "camera-outline",
      "image-multiple-outline",
      "information-outline",
      "translate",
    ],
  },
  {
    label: "Vietnam culture",
    icons: [
      "bank-outline",
      "temple-buddhist",
      "castle",
      "book-open-page-variant-outline",
      "drama-masks",
      "palette-outline",
      "music-note-outline",
      "gift-outline",
      "hand-heart-outline",
    ],
  },
  {
    label: "Mekong nature",
    icons: [
      "waves",
      "ferry",
      "sail-boat",
      "palm-tree",
      "tree-outline",
      "pine-tree",
      "leaf",
      "flower-outline",
      "sprout-outline",
      "terrain",
      "beach",
      "weather-sunset",
      "weather-night",
    ],
  },
  {
    label: "Food and drink",
    icons: [
      "silverware-fork-knife",
      "chef-hat",
      "pot-steam-outline",
      "coffee-outline",
      "cup-water",
      "ice-cream",
      "cake-variant-outline",
      "fish",
      "food-steak",
      "food-apple-outline",
      "beer-outline",
      "glass-cocktail",
    ],
  },
  {
    label: "Stay and services",
    icons: [
      "bed-outline",
      "home-outline",
      "office-building-outline",
      "storefront-outline",
      "shopping-outline",
      "basket-outline",
      "warehouse",
      "briefcase-outline",
      "hospital-box-outline",
      "shower",
      "wifi",
      "parking",
      "shield-check-outline",
      "cash-multiple",
      "wallet-outline",
      "qrcode",
    ],
  },
  {
    label: "Move and activities",
    icons: [
      "airplane",
      "train",
      "bus",
      "car-outline",
      "motorbike",
      "bike",
      "walk",
      "tent",
      "ferris-wheel",
      "binoculars",
      "wheelchair-accessibility",
      "baby-carriage",
      "dog-side",
      "star-outline",
    ],
  },
];

export const CATEGORY_ICON_PRESETS = CATEGORY_ICON_GROUPS.flatMap((group) => group.icons);

export const CATEGORY_ICON_MAP = {
  "map-marker-outline": MapPin,
  "map-search-outline": Search,
  "compass-outline": Compass,
  "sign-direction": Navigation,
  "ticket-confirmation-outline": Ticket,
  "camera-outline": Camera,
  "image-multiple-outline": Image,
  "information-outline": Info,
  translate: Languages,
  "bank-outline": Landmark,
  "temple-buddhist": Landmark,
  castle: Castle,
  "book-open-page-variant-outline": BookOpen,
  "drama-masks": Drama,
  "palette-outline": Palette,
  "music-note-outline": Music,
  "gift-outline": Gift,
  "hand-heart-outline": HeartHandshake,
  waves: Waves,
  ferry: Ship,
  "sail-boat": Sailboat,
  "palm-tree": Trees,
  "tree-outline": Trees,
  "pine-tree": TreePine,
  leaf: Leaf,
  "flower-outline": Flower2,
  "sprout-outline": Sprout,
  terrain: Mountain,
  beach: Waves,
  "weather-sunset": Sun,
  "weather-night": Moon,
  "silverware-fork-knife": Utensils,
  "chef-hat": ChefHat,
  "pot-steam-outline": Soup,
  "coffee-outline": Coffee,
  "cup-water": GlassWater,
  "ice-cream": IceCream,
  "cake-variant-outline": CakeSlice,
  fish: Fish,
  "food-steak": Beef,
  "food-apple-outline": Apple,
  "beer-outline": Beer,
  "glass-cocktail": Wine,
  "bed-outline": Bed,
  "home-outline": Home,
  "office-building-outline": Building2,
  "storefront-outline": Store,
  "shopping-outline": ShoppingBag,
  "basket-outline": ShoppingBasket,
  warehouse: Warehouse,
  "briefcase-outline": Briefcase,
  "hospital-box-outline": Hospital,
  shower: Bath,
  wifi: Wifi,
  parking: CircleParking,
  "shield-check-outline": ShieldCheck,
  "cash-multiple": Banknote,
  "wallet-outline": Wallet,
  qrcode: QrCode,
  airplane: Plane,
  train: Train,
  bus: Bus,
  "car-outline": Car,
  motorbike: Car,
  bike: Bike,
  walk: Footprints,
  tent: Tent,
  "ferris-wheel": FerrisWheel,
  binoculars: Binoculars,
  "wheelchair-accessibility": Accessibility,
  "baby-carriage": Baby,
  "dog-side": Dog,
  "star-outline": Star,
};

const LEGACY_ICON_TO_NAME = {
  Accessibility: "wheelchair-accessibility",
  Baby: "baby-carriage",
  BadgeInfo: "information-outline",
  Bath: "shower",
  BedDouble: "bed-outline",
  Beef: "food-steak",
  Beer: "beer-outline",
  Bike: "bike",
  Binoculars: "binoculars",
  BookOpen: "book-open-page-variant-outline",
  BriefcaseBusiness: "briefcase-outline",
  Building2: "office-building-outline",
  Building: "office-building-outline",
  Bus: "bus",
  Camera: "camera-outline",
  Car: "car-outline",
  CakeSlice: "cake-variant-outline",
  Castle: "castle",
  ChefHat: "chef-hat",
  Church: "temple-buddhist",
  CircleDollarSign: "cash-multiple",
  Coffee: "coffee-outline",
  Compass: "compass-outline",
  Dog: "dog-side",
  Drama: "drama-masks",
  FerrisWheel: "ferris-wheel",
  Fish: "fish",
  Flower2: "flower-outline",
  Footprints: "walk",
  Gift: "gift-outline",
  GlassWater: "cup-water",
  HeartHandshake: "hand-heart-outline",
  Home: "home-outline",
  Hospital: "hospital-box-outline",
  Hotel: "bed-outline",
  House: "home-outline",
  IceCreamBowl: "ice-cream",
  Images: "image-multiple-outline",
  Landmark: "bank-outline",
  Languages: "translate",
  Leaf: "leaf",
  Map: "map-search-outline",
  MapPinned: "map-marker-outline",
  Martini: "glass-cocktail",
  Moon: "weather-night",
  Motorbike: "motorbike",
  Mountain: "terrain",
  MountainSnow: "terrain",
  Music: "music-note-outline",
  Palette: "palette-outline",
  Palmtree: "palm-tree",
  ParkingCircle: "parking",
  Plane: "airplane",
  QrCode: "qrcode",
  Route: "sign-direction",
  Sailboat: "sail-boat",
  Shell: "compass-outline",
  ShieldCheck: "shield-check-outline",
  Ship: "ferry",
  ShipWheel: "ferry",
  ShoppingBag: "shopping-outline",
  ShoppingBasket: "basket-outline",
  Shrimp: "fish",
  Signpost: "sign-direction",
  Soup: "pot-steam-outline",
  Sparkles: "map-search-outline",
  Sprout: "sprout-outline",
  Star: "star-outline",
  Store: "storefront-outline",
  Sun: "weather-sunset",
  Sunrise: "weather-sunset",
  Sunset: "weather-sunset",
  TentTree: "tent",
  Ticket: "ticket-confirmation-outline",
  Train: "train",
  TreePine: "pine-tree",
  Trees: "tree-outline",
  Umbrella: "beach",
  University: "bank-outline",
  UtensilsCrossed: "silverware-fork-knife",
  Vegan: "food-apple-outline",
  WalletCards: "wallet-outline",
  Warehouse: "warehouse",
  Waves: "waves",
  Wifi: "wifi",
};

const CATEGORY_NAME_ICON_RULES = [
  { keywords: ["cho", "market", "shopping", "mua sam"], icon: "basket-outline" },
  { keywords: ["chua", "den", "temple", "pagoda", "nha tho"], icon: "temple-buddhist" },
  { keywords: ["di tich", "lich su", "bao tang", "van hoa"], icon: "bank-outline" },
  { keywords: ["song", "kenh", "ben", "tau", "thuyen", "floating"], icon: "ferry" },
  { keywords: ["bien", "dao", "beach"], icon: "waves" },
  { keywords: ["vuon", "sinh thai", "canh dong", "nature", "park"], icon: "tree-outline" },
  { keywords: ["nui", "mountain", "hang"], icon: "terrain" },
  { keywords: ["an", "am thuc", "food", "restaurant", "quan"], icon: "silverware-fork-knife" },
  { keywords: ["cafe", "coffee", "ca phe", "tra"], icon: "coffee-outline" },
  { keywords: ["khach san", "hotel", "resort", "homestay", "stay"], icon: "bed-outline" },
  { keywords: ["tour", "trip", "trail", "hanh trinh"], icon: "sign-direction" },
  { keywords: ["xe", "bus", "taxi", "di chuyen", "transport"], icon: "bus" },
  { keywords: ["anh", "checkin", "photo", "camera"], icon: "camera-outline" },
  { keywords: ["ve", "ticket", "event", "su kien"], icon: "ticket-confirmation-outline" },
  { keywords: ["tre em", "family", "gia dinh"], icon: "baby-carriage" },
];

const normalizeCategoryText = (value = "") =>
  String(value)
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/g, "d")
    .trim();

export const getCategoryIconName = (category) => {
  const configuredIcon = typeof category === "string" ? category : category?.icon;
  if (configuredIcon && CATEGORY_ICON_MAP[configuredIcon]) return configuredIcon;
  if (configuredIcon && LEGACY_ICON_TO_NAME[configuredIcon])
    return LEGACY_ICON_TO_NAME[configuredIcon];
  const text = normalizeCategoryText(
    typeof category === "string"
      ? category
      : `${category?.name || ""} ${category?.slug || ""}`,
  );
  return (
    CATEGORY_NAME_ICON_RULES.find((rule) =>
      rule.keywords.some((keyword) => text.includes(keyword)),
    )?.icon || DEFAULT_CATEGORY_ICON
  );
};

export const CATEGORY_COLOR_PRESETS = [
  "#EF4444",
  "#F59E0B",
  "#10B981",
  "#3B82F6",
  "#8B5CF6",
  "#EC4899",
  "#06B6D4",
  "#84CC16",
  "#F97316",
  "#6366F1",
];
