export const DEFAULT_CATEGORY_ICON = "map-marker-outline";

export const CATEGORY_ICON_NAMES = new Set([
  "map-marker-outline",
  "map-search-outline",
  "compass-outline",
  "sign-direction",
  "ticket-confirmation-outline",
  "camera-outline",
  "image-multiple-outline",
  "information-outline",
  "translate",
  "bank-outline",
  "temple-buddhist",
  "castle",
  "book-open-page-variant-outline",
  "drama-masks",
  "palette-outline",
  "music-note-outline",
  "gift-outline",
  "hand-heart-outline",
  "waves",
  "ferry",
  "sail-boat",
  "palm-tree",
  "tree-outline",
  "pine-tree",
  "leaf",
  "flower-outline",
  "sprout-outline",
  "terrain",
  "image-filter-hdr-outline",
  "beach",
  "weather-sunset",
  "weather-sunny",
  "weather-night",
  "silverware-fork-knife",
  "chef-hat",
  "pot-steam-outline",
  "coffee-outline",
  "cup-water",
  "ice-cream",
  "cake-variant-outline",
  "fish",
  "food-steak",
  "food-apple-outline",
  "beer-outline",
  "glass-cocktail",
  "bed-outline",
  "home-outline",
  "office-building-outline",
  "storefront-outline",
  "shopping-outline",
  "basket-outline",
  "warehouse",
  "briefcase-outline",
  "hospital-box-outline",
  "shower",
  "wifi",
  "parking",
  "shield-check-outline",
  "cash-multiple",
  "wallet-outline",
  "qrcode",
  "airplane",
  "train",
  "bus",
  "car-outline",
  "motorbike",
  "bike",
  "walk",
  "tent",
  "ferris-wheel",
  "binoculars",
  "wheelchair-accessibility",
  "baby-carriage",
  "dog-side",
  "star-outline",
]);

const LEGACY_ICON_TO_MDI = {
  Accessibility: "wheelchair-accessibility",
  Baby: "baby-carriage",
  BadgeInfo: "information-outline",
  Bath: "shower",
  BedDouble: "bed-outline",
  Beef: "food-steak",
  Beer: "beer-outline",
  Bike: "bike",
  Binoculars: "binoculars",
  BookOpen: "book-open-page-variant-outline",
  BriefcaseBusiness: "briefcase-outline",
  Building2: "office-building-outline",
  Building: "office-building-outline",
  Bus: "bus",
  Camera: "camera-outline",
  Car: "car-outline",
  CakeSlice: "cake-variant-outline",
  Castle: "castle",
  ChefHat: "chef-hat",
  Church: "temple-buddhist",
  CircleDollarSign: "cash-multiple",
  Coffee: "coffee-outline",
  Compass: "compass-outline",
  Dog: "dog-side",
  Drama: "drama-masks",
  FerrisWheel: "ferris-wheel",
  Fish: "fish",
  Flower2: "flower-outline",
  Footprints: "walk",
  Gift: "gift-outline",
  GlassWater: "cup-water",
  HeartHandshake: "hand-heart-outline",
  Home: "home-outline",
  Hospital: "hospital-box-outline",
  Hotel: "hotel-outline",
  House: "home-outline",
  IceCreamBowl: "ice-cream",
  Images: "image-multiple-outline",
  Landmark: "bank-outline",
  Languages: "translate",
  Leaf: "leaf",
  Map: "map-search-outline",
  MapPinned: "map-marker-outline",
  Martini: "glass-cocktail",
  Moon: "weather-night",
  Motorbike: "motorbike",
  Mountain: "terrain",
  MountainSnow: "image-filter-hdr-outline",
  Music: "music-note-outline",
  Palette: "palette-outline",
  Palmtree: "palm-tree",
  ParkingCircle: "parking",
  Plane: "airplane",
  QrCode: "qrcode",
  Route: "map-signs",
  Sailboat: "sail-boat",
  Shell: "shell",
  ShieldCheck: "shield-check-outline",
  Ship: "ferry",
  ShipWheel: "ferry",
  ShoppingBag: "shopping-outline",
  ShoppingBasket: "basket-outline",
  Shrimp: "shrimp",
  Signpost: "map-signs",
  Soup: "pot-steam-outline",
  Sparkles: "map-search-outline",
  Sprout: "sprout-outline",
  Star: "star-outline",
  Store: "storefront-outline",
  Sun: "weather-sunny",
  Sunrise: "weather-sunrise",
  Sunset: "weather-sunset",
  TentTree: "tent",
  Ticket: "ticket-confirmation-outline",
  Train: "train",
  TreePine: "pine-tree",
  Trees: "tree-outline",
  Umbrella: "beach",
  University: "bank-outline",
  UtensilsCrossed: "silverware-fork-knife",
  Vegan: "food-apple-outline",
  WalletCards: "wallet-outline",
  Warehouse: "warehouse",
  Waves: "waves",
  Wifi: "wifi",
};

export function normalizeCategoryIcon(value) {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  if (CATEGORY_ICON_NAMES.has(trimmed)) return trimmed;
  const legacyIcon = {
    Hotel: "bed-outline",
    Route: "sign-direction",
    Shell: "compass-outline",
    Shrimp: "fish",
    Signpost: "sign-direction",
    Sunrise: "weather-sunset",
  }[trimmed] || LEGACY_ICON_TO_MDI[trimmed];
  return CATEGORY_ICON_NAMES.has(legacyIcon) ? legacyIcon : null;
}

export function isCategoryIconName(value) {
  return CATEGORY_ICON_NAMES.has(value);
}
