/**
 * Cấu trúc mặc định đồng bộ với web/src/pages/admin/settings/defaultSettings.js
 */
export const DEFAULT_SYSTEM_SETTINGS = {
  general: {
    siteName: "Đi Đâu Giờ?",
    siteDescription: "Khám phá Cần Thơ",
    logoUrl: "",
    faviconUrl: "",
    language: "vi",
    timezone: "Asia/Ho_Chi_Minh",
    dateFormat: "DD/MM/YYYY",
    currency: "VND",
    baseUrl: "https://didaugio.vn",
    domain: "didaugio.vn",
    maintenanceMode: false,
  },
  mapDefault: {
    latitude: "10.0452",
    longitude: "105.7469",
    zoom: "13",
  },
  email: {
    smtpHost: "",
    smtpPort: "587",
    defaultFromEmail: "noreply@didaugio.vn",
    useTLS: true,
    useSSL: false,
    notificationsEnabled: true,
  },
  security: {
    require2FA: false,
    lockoutEnabled: true,
    sessionTimeoutMinutes: "30",
    csrfProtection: true,
    xssProtection: true,
    secureApiLogin: true,
  },
  modules: {
    placeApproval: true,
    routing: true,
    aiPlanner: true,
    notifications: true,
    newsModule: false,
    reportsModule: true,
    cacheEnabled: true,
    maxUploadSizeMb: "20",
    allowedFileTypes: "jpg,jpeg,png,webp,pdf",
  },
  integrations: {
    googleApiKey: "",
    facebookAppId: "",
    webhookEndpoint: "",
    paymentProvider: "none",
    analyticsProvider: "ga4",
  },
  logs: {
    auditLogEnabled: true,
    errorLogEnabled: true,
    retentionDays: "30",
    allowLogAccess: true,
  },
  operations: {
    backupEnabled: true,
    backupFrequency: "daily",
    offlinePageMessage: "Hệ thống đang bảo trì, vui lòng quay lại sau.",
  },
  seo: {
    metaTitleDefault: "Đi Đâu Giờ - Khám phá Cần Thơ",
    metaDescriptionDefault: "Nền tảng khám phá địa điểm nổi bật tại Cần Thơ",
    robotsPolicy: "index,follow",
    sitemapEnabled: true,
    headerCustomCode: "",
    footerCustomCode: "",
  },
};
