export const NAVIGATION_STATES = Object.freeze({
  IDLE: "IDLE",
  CALCULATING: "CALCULATING",
  NAVIGATING: "NAVIGATING",
  APPROACHING: "APPROACHING",
  REROUTING: "REROUTING",
  SUSPENDED: "SUSPENDED",
  ARRIVED: "ARRIVED",
});

export const NAVIGATION_EVENTS = Object.freeze({
  START: "START",
  ROUTE_READY: "ROUTE_READY",
  OFF_ROUTE_CONFIRMED: "OFF_ROUTE_CONFIRMED",
  NEAR_TURN: "NEAR_TURN",
  PASSED_TURN: "PASSED_TURN",
  NEAR_DESTINATION: "NEAR_DESTINATION",
  ARRIVED: "ARRIVED",
  GPS_LOST: "GPS_LOST",
  GPS_FOUND: "GPS_FOUND",
  CONFIRM_ARRIVAL: "CONFIRM_ARRIVAL",
  CANCEL: "CANCEL",
});

const TRANSITIONS = Object.freeze({
  [NAVIGATION_STATES.IDLE]: {
    [NAVIGATION_EVENTS.START]: NAVIGATION_STATES.CALCULATING,
    [NAVIGATION_EVENTS.ROUTE_READY]: NAVIGATION_STATES.NAVIGATING,
  },
  [NAVIGATION_STATES.CALCULATING]: {
    [NAVIGATION_EVENTS.ROUTE_READY]: NAVIGATION_STATES.NAVIGATING,
    [NAVIGATION_EVENTS.CANCEL]: NAVIGATION_STATES.IDLE,
    [NAVIGATION_EVENTS.GPS_LOST]: NAVIGATION_STATES.SUSPENDED,
  },
  [NAVIGATION_STATES.NAVIGATING]: {
    [NAVIGATION_EVENTS.OFF_ROUTE_CONFIRMED]: NAVIGATION_STATES.REROUTING,
    [NAVIGATION_EVENTS.NEAR_TURN]: NAVIGATION_STATES.APPROACHING,
    [NAVIGATION_EVENTS.NEAR_DESTINATION]: NAVIGATION_STATES.APPROACHING,
    [NAVIGATION_EVENTS.ARRIVED]: NAVIGATION_STATES.ARRIVED,
    [NAVIGATION_EVENTS.GPS_LOST]: NAVIGATION_STATES.SUSPENDED,
    [NAVIGATION_EVENTS.CANCEL]: NAVIGATION_STATES.IDLE,
  },
  [NAVIGATION_STATES.APPROACHING]: {
    [NAVIGATION_EVENTS.PASSED_TURN]: NAVIGATION_STATES.NAVIGATING,
    [NAVIGATION_EVENTS.OFF_ROUTE_CONFIRMED]: NAVIGATION_STATES.REROUTING,
    [NAVIGATION_EVENTS.ARRIVED]: NAVIGATION_STATES.ARRIVED,
    [NAVIGATION_EVENTS.GPS_LOST]: NAVIGATION_STATES.SUSPENDED,
    [NAVIGATION_EVENTS.CANCEL]: NAVIGATION_STATES.IDLE,
  },
  [NAVIGATION_STATES.REROUTING]: {
    [NAVIGATION_EVENTS.ROUTE_READY]: NAVIGATION_STATES.NAVIGATING,
    [NAVIGATION_EVENTS.GPS_LOST]: NAVIGATION_STATES.SUSPENDED,
    [NAVIGATION_EVENTS.CANCEL]: NAVIGATION_STATES.IDLE,
  },
  [NAVIGATION_STATES.SUSPENDED]: {
    [NAVIGATION_EVENTS.GPS_FOUND]: NAVIGATION_STATES.NAVIGATING,
    [NAVIGATION_EVENTS.CANCEL]: NAVIGATION_STATES.IDLE,
  },
  [NAVIGATION_STATES.ARRIVED]: {
    [NAVIGATION_EVENTS.CONFIRM_ARRIVAL]: NAVIGATION_STATES.IDLE,
    [NAVIGATION_EVENTS.CANCEL]: NAVIGATION_STATES.IDLE,
  },
});

export function transitionNavigationState(currentState, event) {
  const eventType = typeof event === "string" ? event : event?.type;
  return TRANSITIONS[currentState]?.[eventType] ?? currentState;
}

export function navigationReducer(state, event) {
  const current = state?.state ?? NAVIGATION_STATES.IDLE;
  const nextState = transitionNavigationState(current, event);
  return {
    ...state,
    state: nextState,
    lastEvent: typeof event === "string" ? event : event?.type ?? null,
  };
}
