export const ENDPOINTS = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    loginGoogle: "/auth/google",
    refresh: "/auth/refresh",
    me: "/auth/me",
    logout: "/auth/logout",
    ping: "/auth/ping",
    verifyEmailOtp: "/auth/verify-email-otp",
    resendVerificationPublic: "/auth/resend-verification-public",
  },
  places: {
    home: "/places/home",
    list: "/places",
    services: "/places/services",
    detail: (id) => `/places/${id}`,
    detailBySlug: (slug) => `/places/slug/${slug}`,
    reviews: (id) => `/places/${id}/reviews`,
    myReview: (id) => `/places/${id}/reviews/me`,
  },
  categories: {
    list: "/categories",
  },
  profile: {
    get: "/profile",
    summary: "/profile/summary",
    update: "/profile",
    updateAvatar: "/profile/avatar",
    savedPlaces: "/profile/saved-places",
    savedPlaceById: (placeId) => `/profile/saved-places/${placeId}`,
    savedCollections: "/profile/saved-collections",
    savedCollectionByName: (name) =>
      `/profile/saved-collections/${encodeURIComponent(name)}`,
    savedTrips: "/profile/saved-trips",
    savedTripById: (tripId) => `/profile/saved-trips/${tripId}`,
    trips: "/profile/trips",
    generateTrip: "/profile/trips/generate",
    createTrip: "/profile/trips",
    tripDetail: (id) => `/profile/trips/${id}`,
    updateTrip: (id) => `/profile/trips/${id}`,
    deleteTrip: (id) => `/profile/trips/${id}`,
    duplicateTrip: (id) => `/profile/trips/${id}/duplicate`,
    addDestination: (tripId) => `/profile/trips/${tripId}/destinations`,
    removeDestination: (tripId, destId) =>
      `/profile/trips/${tripId}/destinations/${destId}`,
    linkBookingToTrip: (tripId, bookingId) =>
      `/profile/trips/${tripId}/bookings/${bookingId}/link`,
    reorderTripStops: (tripId) => `/profile/trips/${tripId}/stops/reorder`,
    moveTripStop: (tripId, stopId) => `/profile/trips/${tripId}/stops/${stopId}/move`,
    tripSession: (tripId) => `/profile/trips/${tripId}/session`,
    updateDestination: (tripId, destId) => `/profile/trips/${tripId}/destinations/${destId}`,
    tripShare: (id) => `/profile/trips/${id}/share`,
    tripShareById: (tripId, shareId) => `/profile/trips/${tripId}/share/${shareId}`,
    accessTripShare: (shareCode) => `/profile/shared-trip/${shareCode}`,
    deleteTripShare: (shareId) => `/profile/trips/share/${shareId}`,
    bookings: "/profile/bookings",
    bookingDetail: (id) => `/profile/bookings/${id}`,
    bookingQr: (id) => `/profile/bookings/${id}/qr`,
    bookingCancel: (id) => `/profile/bookings/${id}/cancel`,
    pushToken: "/profile/push-token",
    notifications: "/profile/notifications",
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    markRead: (id) => `/notifications/${id}/read`,
    markAllRead: "/notifications/mark-all-read",
    testPush: "/notifications/test-push",
  },
  booking: {
    createByService: (serviceId) => `/services/${serviceId}/book`,
    create: "/business/bookings",
    list: "/business/bookings",
    detail: (id) => `/business/bookings/${id}`,
    publicAvailability: (serviceId) => `/bookings/availability/${serviceId}`,
  },
  payments: {
    checkout: "/payments/checkout",
    detail: (id) => `/payments/${id}`,
    byBooking: (bookingId) => `/payments/by-booking/${bookingId}`,
  },
  ai: {
    placeSummary: "/ai/place-summary",
    chat: "/ai/chat",
    navigate: "/ai/navigate",
    groqChat: "/ai/groq-chat",
    voiceTranscribe: "/ai/voice/transcribe",
    voiceSpeech: "/ai/voice/speech",
  },
  routing: {
    health: "/routes/health",
    calculate: "/routes/calculate",
    legs: "/routes/legs",
  },
  navigation: {
    navigate: "/navigation/navigate",
    telemetry: "/navigation/telemetry",
  },
  boundaries: {
    districts: "/boundaries/districts",
    wards: "/boundaries/wards",
  },
  feedback: "/feedback",
  events: {
    list: "/events",
    detail: (id) => `/events/${id}`,
    join: (id) => `/events/${id}/join`,
    ping: (id) => `/events/${id}/ping`,
    moments: (id) => `/events/${id}/moments`,
    deleteMoment: (momentId) => `/events/moments/${momentId}`,
  },
  cms: {
    exploreLanding: "/cms/explore-landing",
    banners: "/cms/banners",
    featuredPlaces: "/cms/featured-places",
    sampleTrips: "/cms/sample-trips",
    announcements: "/cms/announcements",
  },
};
